import jwt from "jsonwebtoken";

// @desc generate jwt token for authentication
// @param take the unique user id generated by the mongodb
// @param take the env variable JWT_SECRET
const generateToken = (id) => {
  return jwt.sign({ id }, process.env.JWT_SECRET, {
    expiresIn: "30d",
  });
};

export default generateToken;
